FROM rust:1-bullseye AS dev
WORKDIR /app

ENV CARGO_TARGET_DIR=/app/target

RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo 'fn main() {}' > src/main.rs
RUN cargo build
RUN rm -rf src

COPY . .

CMD ["sh", "-c", "exec cargo watch --watch-when-idle -x 'run'"]

